# Generated by Django 4.2 on 2024-01-23 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherquestion',
            name='answer_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='teacherquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to='file/images'),
        ),
        migrations.AddField(
            model_name='teacherquestion',
            name='question_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherquestion',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherquestion',
            name='title',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
