# Generated by Django 4.2 on 2024-01-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_teacherquestion_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherquestion',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
