# Generated by Django 4.2 on 2024-01-23 20:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_teacherquestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='file/images', validators=[api.models.image_size_check]),
        ),
    ]
