# Generated by Django 4.2 on 2024-01-24 09:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_teacherquestion_apendix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherquestion',
            name='apendix',
            field=models.FileField(null=True, upload_to='uploaded_files/apendix', validators=[api.models.file_size_check]),
        ),
        migrations.AlterField(
            model_name='teacherquestion',
            name='image',
            field=models.ImageField(null=True, upload_to='uploaded_files/images', validators=[api.models.image_size_check]),
        ),
    ]
