# Generated by Django 4.2 on 2024-01-24 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_teacherquestion_apendix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qgptquestion',
            name='answer_text',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='qgptquestion',
            name='title',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qgptquestion',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherquestion',
            name='answer_text',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='teacherquestion',
            name='title',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherquestion',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
