# Generated by Django 4.2 on 2024-01-24 11:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_qgptquestion_answer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherquestion',
            name='apendix',
        ),
        migrations.AddField(
            model_name='teacherquestion',
            name='appendix',
            field=models.FileField(null=True, upload_to='uploaded_files/appendix', validators=[api.models.file_size_check]),
        ),
    ]
