# Generated by Django 4.2 on 2024-01-24 13:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_teacherquestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherquestion',
            name='image',
        ),
        migrations.AddField(
            model_name='teacherquestion',
            name='12',
            field=models.ImageField(null=True, upload_to='uploaded_files/images', validators=[api.models.image_size_check]),
        ),
    ]
