# Generated by Django 4.2 on 2024-01-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_teacherquestion_image_teacherquestion_12'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherquestion',
            old_name='12',
            new_name='image',
        ),
    ]
